version: '3.8'
services:
  grain:
    build:
      context: https://github.com/0ceanSlim/grain.git
      dockerfile: docs/docker/Dockerfile
    image: grain_local:latest
    container_name: grain_relay
    restart: unless-stopped
    ports:
      - "8181:8181"
    volumes:
      - grain_data:/data
    environment:
      - SERVER_PORT=8181

volumes:
  grain_data:
