version: '3.8'
services:
  mongo:
    image: mongo:7.0
    container_name: grain-mongo
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db

  grain:
    build:
      context: https://github.com/0ceanSlim/grain.git
      dockerfile: docs/docker/Dockerfile
    image: grain_local:latest
    pull_policy: never
    container_name: grain-relay
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - grain_data:/data
    environment:
      - SERVER_PORT=8181
      - MONGODB_URI=mongodb://localhost:27017
    depends_on:
      - mongo

networks:
  grain_internal:
    driver: bridge

volumes:
  grain_data:
  mongo_data:
